default:
  image: klakegg/hugo:ubuntu-ci

stages:
  - build

build:
  stage: build
  script:
    - hugo -d ./dist -v
    - rm -rf /var/www/html/ateliertraviole/*
    - cp -r ./dist/* /var/www/html/ateliertraviole/
