default:
  image: klakegg/hugo:ubuntu-ci

stages:
  - build

build:
  stage: build
  script:
    - hugo -d ../dist -s site -v
    - rm -rf /var/www/html/atelier-traviole/*
    - cp -r ./dist/* /var/www/html/atelier-traviole/
