baseURL = 'https://ateliertraviole.fr'
languageCode = 'fr'
title = 'Atelier Traviole'
paginate = 6
staticDir = ['static']
theme = 'traviole'
defaultContentLanguage = 'fr'

copyright = 'All rights reserved.'
[author]
  name = 'Léna Desmettre'
  email = 'lena@ateliertraviole.fr'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 2
  [languages.fr]
    languageName = 'Français'
    weight = 1


[params]
  siteName = 'Atelier Traviole'
  siteDesc = 'Atelier Traviole'
  author = 'Lena Desmettre'

[taxonomies]
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = false
    [markup.goldmark.renderer]
      hardWraps = false
