baseURL = 'https://ateliertraviole.fr'
languageCode = 'fr'
title = 'Atelier Traviole'
paginate = 6
staticDir = ['static']

copyright = 'All rights reserved.'
[author]
  name = 'Léna Desmettre'
  email = 'lena@ateliertraviole.fr'

defaultContentLanguage = 'fr'

[languages]
  [languages.fr]
    languageName = 'Français'
    title = 'En Français'
    weight = 2
  [languages.en]
    languageName = 'English'
    title = 'In English'
    weight = 1


[params]
  siteName = 'Atelier Traviole'
  siteDesc = 'Atelier Traviole'
  author = 'Lena Desmettre'

[taxonomies]
  tag = 'tags'

[markup]
  defaultMarkdownHandler = 'goldmark'

