baseURL = 'https://ateliertraviole.fr'
languageCode = 'fr-fr'
title = 'Atelier Traviole'
paginate = 6
staticDir = ['static']

[params]
    siteName = 'Atelier Traviole'
    siteDesc = 'Atelier Traviole'
    author = 'Lena Desmettre'

[taxonomies]
    tag = 'tags'
    project = 'projects'

