backend:
  name: gitlab
  repo: nabos/atelier-traviole
  branch: netlify
  auth_type: pkce
  app_id: f51ddce80814196824ce8ed872d89326ff702f66c99004296f7a84b8ea531c92
  api_root: https://git.glargh.fr/api/v4
  base_url: https://git.glargh.fr
  auth_endpoint: oauth/authorize

media_folder: "static/img"
public_folder: "img"

i18n:
  structure: multiple_files
  locales: [fr, en]

headers:
  for: "/*"
  values:
    - Access-Control-Allow-Origin = "*"


collections:
  - name: "portfolio"
    label: "Piece of Art"
    slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}"
    folder: "site/content/portfolio"
    path: '{{slug}}/index'
    create: false
    i18n: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        default: "Portfolio"
      - label: "Lines"
        name: "lines"
        widget: "list"
        i18n: true
        field:
          label: "Pieces"
          name: "pieces"
          widget: "list"
          fields:
          - {label: "Title", name: "title", widget: "string", i18n: true}
          - {label: "Subtitle", name: "subtitle", widget: "string", i18n: true}
          - {label: "Aspect", name: "aspect", widget: "select", options: ["square", "a4", "card", "a3--horizontal"]}
          - {label: "Project", name: "project", widget: "relation", collection: "projects", search_fields: ["title"], value_field: "slug", display_fields: ["title"], required: false}
          - {label: "Cover", name: "image", widget: "image", required: false}
          - {label: "CoverAlt", name: "imageAlt", widget: "string", i18n: true}
          - {label: "Description", name: "description", widget: "text", i18n: true}
          - {label: "Links", name: "links", widget: "list", required: false, summary: "{{fields.label}}", i18n: true, fields: [
              {label: "Label", name: "label", widget: "string"},
              {label: "Link", name: "link", widget: "string"}]}
  - name: "projects"
    label: "Project"
    slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}"
    folder: "site/content/projects"
    path: '{{slug}}/index'
    create: true
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Subtitle", name: "subtitle", widget: "string", i18n: true}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", required: false, i18n: true, field: {label: "Tag", name: "tag", widget: "string"}}
      - {label: "Cover", name: "image", widget: "image", required: false}
      - {label: "CoverAlt", name: "imageAlt", widget: "string", i18n: true}
      - {label: "Description", name: "description", widget: "text", i18n: true}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}
  - name: "links"
    label: "Link"
    slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}"
    folder: "site/content/links"
    preview_path: "/links/"
    create: false
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Links"}
      - {label: "Links", name: "links", widget: "list", required: false, i18n: true, fields: [
          {label: "Label", name: "label", widget: "string"},
          {label: "Link", name: "link", widget: "string"}]}
  - name: "contact"
    identifier_field: "description"
    label: "Contact"
    folder: "site/content/contact"
    create: false
    i18n: true
    fields:
      - {label: "Description", name: "description", widget: "markdown", i18n: true}
      - {label: "Contact paragraph", name: "contact", widget: "markdown", i18n: true}
