backend:
  name: gitlab
  repo: nabos/atelier-traviole
  branch: netlify
  auth_type: pkce
  app_id: 663435257b5e43b17bdc9f71688373f6dcf6da2b2931364e4e168d60571f9f3b
  api_root: https://git.glargh.fr/api/v4
  base_url: https://git.glargh.fr
  auth_endpoint: oauth/authorize

media_folder: "static/img"
public_folder: "img"

i18n:
  structure: multiple_files
  locales: [fr, en]

collections:
  - name: "portfolio"
    label: "Piece of Art"
    slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}"
    folder: "content/portfolio"
    path: '{{slug}}/_index'
    create: true
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Subtitle", name: "subtitle", widget: "string", i18n: true}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Order", name: "order", widget: "number", value_type: "int"}
      - {label: "Project", name: "project", widget: "relation", collection: "projects", search_fields: ["title"], value_field: "slug", display_fields: ["title"], required: false}
      - {label: "Cover", name: "image", widget: "image", required: false}
      - {label: "CoverAlt", name: "imageAlt", widget: "string", i18n: true}
      - {label: "Description", name: "description", widget: "text", i18n: true}
      - {label: "Links", name: "links", widget: "list", required: false, fields: [
          {label: "Label", name: "label", widget: "string"},
          {label: "Link", name: "link", widget: "string"}]}
  - name: "projects"
    label: "Project"
    slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}"
    folder: "content/projects"
    path: '{{slug}}/_index'
    create: true
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Subtitle", name: "subtitle", widget: "string", i18n: true}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover", name: "image", widget: "image", required: false}
      - {label: "CoverAlt", name: "imageAlt", widget: "string", i18n: true}
      - {label: "Description", name: "description", widget: "text", i18n: true}
  - name: "links"
    label: "Link"
    slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}"
    folder: "content/links"
    preview_path: "/links/"
    create: false
    i18n: true
    fields:
      - {label: "Links", name: "links", widget: "list", required: false, i18n: true, fields: [
          {label: "Label", name: "label", widget: "string"},
          {label: "Link", name: "link", widget: "string"}]}
  - name: "contact"
    identifier_field: "description"
    label: "Contact"
    folder: "content/contact"
    create: false
    i18n: true
    fields:
      - {label: "Description", name: "description", widget: "markdown", i18n: true}
      - {label: "Contact paragraph", name: "contact", widget: "markdown", i18n: true}
