backend:
  name: gitlab
  repo: nabos/atelier-traviole
  branch: netlify
  auth_type: pkce
  app_id: 663435257b5e43b17bdc9f71688373f6dcf6da2b2931364e4e168d60571f9f3b
  api_root: https://git.glargh.fr/api/v4
  base_url: https://git.glargh.fr
  auth_endpoint: oauth/authorize


media_folder: "static/img"
public_folder: "img"

collections:
  - name: "portfolio"
    label: "Piece of Art"
    folder: "content/portfolio"
    path: '{{slug}}/_index'
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Order", name: "order", widget: "number", value_type: "int"}
      - {label: "Project", name: "project", widget: "relation", collection: "projects", search_fields: ["title"], value_field: "slug", display_fields: ["title"], required: false}
      - {label: "Cover", name: "image", widget: "image"}
      - {label: "CoverAlt", name: "imageAlt", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
  - name: "projects"
    label: "Project"
    folder: "content/projects"
    path: '{{slug}}/_index'
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Slug", name: "slug", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Cover", name: "image", widget: "image", required: false}
      - {label: "CoverAlt", name: "imageAlt", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
  - name: "links"
    label: "Link"
    folder: "content/links"
    create: true
    fields:
      - {label: "Label", name: "label", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
  - name: "contact"
    label: "Contact"
    folder: "content/contact"
    create: false
    fields:
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Contact paragraph", name: "contact", widget: "string"}
